Repository Susmita-Dey/all-round-calculator, pull requests merged in 2022-10, with the labels that each got.

#30 Real time values for currency conversion
  docs/mFunc/getCurrency.md
  package/.gitignore
  package/Functions/Currency.js
  package/package.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, approved

#36 fix: Seperate the functions in `index.js` in different modules
  package/Functions/AgeCalculation.js
  package/Functions/LoanCalculation.js
  package/Functions/RadixConversion.js
  package/Functions/ScientificCalculation.js
  package/Functions/TimeCalculation.js
  package/index.js
Labels: file structure, hacktoberfest-accepted

#35 feat: dynamic doInc and doDecr
  package/index.js
Labels: enhancement, hacktoberfest-accepted

#40 feat: added square root functionality
  package/index.js
Labels: enhancement, hacktoberfest-accepted

#43 Fix documentation
  docs/README.md
Labels: documentation, hacktoberfest-accepted, approved

#44 feat: added percentage funcitonality
  package/index.js
Labels: enhancement, hacktoberfest-accepted, approved

#47 Fixed the errors
  docs/README.md
Labels: documentation, hacktoberfest-accepted

#53 Create a new functionality to calculate sin of given value in degrees
  package/index.js
Labels: enhancement, hacktoberfest-accepted, approved

#55 feat: added generate random number functionality
  package/index.js
Labels: enhancement, hacktoberfest-accepted, approved

#49 feat: added logarithmic function value in package
  package/index.js
Labels: enhancement, hacktoberfest-accepted, approved

#52 add method to calculate power of a number
  docs/aFunc/doPower.md
  docs/functions.md
  package/index.js
Labels: enhancement, hacktoberfest-accepted, approved
